cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add_to_cart/', views.AddToCart.as_view(), name='add_to_cart'),
    path('cart_list/', views.CartList.as_view(), name='cart_list'),
    path('cart_list/<int:id>/', views.CartDetail.as_view(), name='cart_detail'),
    path('cart_list/<int:id>/update/', views.ChangeCart.as_view(), name='change_in_cart'),
    path('cart_list/<int:id>/delete/', views.DeleteFromCart.as_view(), name='delete_from_cart')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('', include('hashtags.urls')),
    path('', include('cart.urls')),
    path('', include('parser.urls')),
    path('', include('employee.urls')),
    path('', include('dishes.urls'))
]


urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                     document_root=settings.STATIC_ROOT)    

library/models.py
from django.db import models

class Books(models.Model):
    GENRE_CHOICES = (
        ('Horror', 'Ужасы'),
        ('Comedy', 'Комедия'),
        ('Fantasy', 'Фэнтези')
    )
    image = models.ImageField(verbose_name='Загрузите изображение', upload_to='books/')
    title = models.CharField(max_length=100, verbose_name='Введите название книги')
    description = models.TextField(verbose_name='Введите описание книги', blank=True)
    price = models.PositiveIntegerField(verbose_name='Введите цену', default=120)
    created_at = models.DateTimeField(auto_now_add=True)
    genre = models.CharField(max_length=100, choices=GENRE_CHOICES, verbose_name='Выберите жанр')
    email = models.CharField(max_length=120, verbose_name='Введите адрес электронной почты')
    director = models.CharField(max_length=100, verbose_name='Введите имя режиссера', default='Исманкулов Нурсултан')
    trailer = models.URLField(verbose_name='Вставьте ссылку на трейлер')


    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'
        
    def __str__(self):
        return f'{self.title}'
    
    
class Reviews(models.Model):
    STARS = (
        ("⭐","⭐"),
        ("⭐⭐","⭐⭐"),
        ("⭐⭐⭐","⭐⭐⭐"),
        ("⭐⭐⭐⭐","⭐⭐⭐⭐"),
        ("⭐⭐⭐⭐⭐","⭐⭐⭐⭐⭐"),
    )
        
    reviews_choice = models.ForeignKey(Books, on_delete=models.CASCADE, related_name='books')
    created_at = models.DateField(auto_now_add=True)
    comment = models.TextField()
    stars = models.CharField(max_length=100, choices=STARS, default='⭐⭐⭐')
    
    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        
    def __str__(self):
        return f'{self.comment}:{self.stars}'

templates/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cart</title>
</head>
<body>
    <form action="/add_review/" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить комментарий</button>
    </form>
</body>
</html>

templates/book.html
{% load static %}
{% include "components/header.html" %}

<link rel="stylesheet" href="{% static 'css/book.css' %}">
<link rel="stylesheet" href="{% static 'css/book_detail.css' %}">

<!-- Контент с карточками -->
<div class="container mt-4 content">
    <div class="row justify-content-center">
        <!-- Пример карточки книги -->
         {% for i in book_list%}
        
        <div class="col-md-4 mb-4">
            <div class="card" style="width: 100%;">
                <img src="{{ i.image.url }}" class="card-img-top" alt="Обложка книги">
                <div class="card-body">
                    <h5 class="card-title">{{ i.title }}</h5>
                    <p class="card-text">{{ i.created_at }}</p>
                    <a href="/book_detail/{{i.id}}" class="btn btn-primary">Подробнее</a>
                </div>
            </div>
        </div>
        <!-- Добавьте дополнительные карточки книг здесь -->
        {% endfor %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</div>

{% include "components/footer.html" %}

<!-- Футер -->

templates/book_detail.html
{% load static %}
{% include "components/header.html" %}
<!-- Контент с информацией о книге -->

<div class="container mt-4">
    <div class="book-card">
        <div class="card">
            <!-- Отображение изображения книги -->
            <img src="{{ book.image.url }}" class="card-img-top" alt="{{ book.title }}">

            <div class="card-body">
                
                <h5 class="card-title">{{ book.title }}</h5>
                
                <p class="card-text">{{ book.description }}</p>
                
                <p><strong>Цена:</strong> ${{ book.price }}</p>
                
                <p><strong>Дата выхода:</strong> {{ book.created_at|date:"Y-m-d" }}</p>
                
                <p><strong>Жанр:</strong> {{ book.get_genre_display }}</p>
                
                <p><strong>Почта:</strong> {{ book.email }}</p>
                
                <p><strong>Автор:</strong> {{ book.director }}</p <iframe width="100%" height="315"
                    src="{{ book.trailer }}" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
    </div>


    <!-- Блок для комментариев -->
    {% for i in book.books.all %}
    <div class="comment-section">
         <h5>Комментарии</h5>
         <div class="comment">
             <p>{{i.created_at}}: {{i.comment}} <strong>Оценка:</strong> {{i.stars}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    
    <!-- Футер -->
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
    <link rel="stylesheet" href="{% static 'css/book_detail.css' %}">
    {% include "components/footer.html"}
</body>

</html>