cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add_to_cart/', views.AddToCart.as_view(), name='add_to_cart'),
    path('cart_list/', views.CartList.as_view(), name='cart_list'),
    path('cart_list/<int:id>/', views.CartDetail.as_view(), name='cart_detail'),
    path('cart_list/<int:id>/update/', views.ChangeCart.as_view(), name='change_in_cart'),
    path('cart_list/<int:id>/delete/', views.DeleteFromCart.as_view(), name='delete_from_cart')
]

employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('user_list/', views.UserListView.as_view(), name='user_list'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('', include('hashtags.urls')),
    path('', include('cart.urls')),
    path('', include('parser.urls')),
    path('', include('employee.urls')),
    path('', include('dishes.urls'))
]


urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                     document_root=settings.STATIC_ROOT)    

dishes/models.py
from django.db import models

class Recipe(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    
    
    def __str__(self):
        return self.title
    
class Ingredient(models.Model):
    UNIT = (
        ('Г','Грамм'),
        ('Кг','Килограмм'),
        ('Мл','Миллилитр'),
        ('Л','Литр'),
        ('Шт','Штука')
    )
    
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='recipe')
    name = models.CharField(max_length=50)
    quantity = models.PositiveIntegerField(default=1)
    unit = models.CharField(choices=UNIT, max_length=10)
    
    def __str__(self):
        return f'{self.name} - {self.unit}'
    

templates/components/footer.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/book.css' %}">
<link rel="stylesheet" href="{% static 'css/book_detail.css' %}">

<footer style="position: absolute; bottom: 0px; width: 100%;">
    © 2024 Ваш Сайт:
    <a class="text-reset fw-bold" href="#" style="color: yellow;">ВашСайт.com</a>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

templates/components/header.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail Book</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="shortcut icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9RaqWhNrT68sVwQFo4ZAs1VRsUZImppmaqg&s">

</head>
<body>

<!-- Навигационная панель -->
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top"
     style="background: linear-gradient(to right, #1a1919, #100f0f);">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="https://lh5.googleusercontent.com/yzWtzlXIlHfLjcFkr0S7UgmoX9HFoJ6VRszWZyEt-G85Gl5ID_XxoLX6Ji6E223S-EU2UUt2Y89uOwkm0tr8KkLQbM4Su17ln5HVBLaLHfxFIqm4DDpwmzPhfeAg1mja2Xdz7JkCvJqbpoEOT0CX8Cg"
                 alt="Logo" style="width: 40px; height: 40px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'book_list' %}" style="color: yellow;">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'all_products' %}" style="color: yellow;">Хэш теги</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false" style="color: yellow;">
                        Мои заказы
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'add_to_cart' %}">Добавить</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'cart_list' %}">Корзина</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'employee:register' %}" style="color: yellow;">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'parsed_book' %}" style="color: yellow;">Другие книги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'parsed_form' %}" style="color: yellow;">Парсить</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'add_review' %}" style="color: yellow;">Оставить комментарий</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false" style="color: yellow;">
                        Мои Рецепты
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'add_recipe' %}">Добавить Рецепт</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'recipe_list' %}">Рецепты</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex" role="search" action="{% url 'search' %}" method="GET">
                <input name="q" type="text" class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
                <button class="btn btn-outline-success" type="submit" style="color: yellow; border-color: yellow;">
                    Поиск
                </button>
            </form>
        </div>
    </div>
</nav>